config_mnist = {}
config_mnist['data_shape'] = [28, 28, 1]
config_mnist['batch_size'] = 100
config_mnist['batch_norm'] = True
config_mnist['batch_norm_eps'] = 1e-05
config_mnist['batch_norm_decay'] = 0.9
config_mnist['e_num_filters'] = 1024
config_mnist['e_num_layers'] = 4
config_mnist['g_num_filters'] = 1024
config_mnist['g_num_layers'] = 3

config_mnist['d_num_filters'] = 512
config_mnist['d_num_layers'] = 4
config_mnist['adam_beta1'] = 0.5
config_mnist['lr'] = 0.002
config_mnist['lr_adv'] = 0.002
config_mnist['epoch_num'] = 800
config_mnist['print_every'] = 200
config_mnist['init_std'] = 0.0099999
config_mnist['init_bias'] = 0.0
config_mnist['conv_filters_dim'] = 4
config_mnist['latent_dim'] = 10
config_mnist['num_cluster'] = 10
config_mnist['work_dir'] = 'results_dsprites'
config_mnist['save_every_epoch'] = 10000
config_mnist['e_noise'] = 'add_noise'
config_mnist['GS'] = 'GS'
config_mnist['noise'] = 'fl'
config_mnist['clamp_lower'] = -0.01
config_mnist['clamp_upper'] = 0.01
config_mnist['is_sklearn'] = False
config_mnist['Cluster'] = 'KMeans'
config_mnist['e_arch'] = 'dcgan'
config_mnist['name'] = 'MNIST'
config_mnist['optimizer'] = 'ADM'
config_mnist['range'] = 4

config_fashion = {}
config_fashion['data_shape'] = [28, 28, 1]
config_fashion['batch_size'] = 100
config_fashion['batch_norm'] = True
config_fashion['batch_norm_eps'] = 1e-05
config_fashion['batch_norm_decay'] = 0.9
# config_mnist['e_num_filters'] = [500, 500,500,500]
# config_mnist['e_num_layers'] = 4
# config_mnist['g_num_filters'] = [500,500,500]
# config_mnist['g_num_layers'] = 3

config_fashion['e_num_filters'] = 1024
config_fashion['e_num_layers'] = 4
config_fashion['g_num_filters'] = 1024
config_fashion['g_num_layers'] = 3

config_fashion['d_num_filters'] = 512
config_fashion['d_num_layers'] = 4
config_fashion['adam_beta1'] = 0.5
config_fashion['lr'] = 0.002
config_fashion['lr_adv'] = 0.002
config_fashion['epoch_num'] = 800
config_fashion['print_every'] = 200
config_fashion['init_std'] = 0.0099999
config_fashion['init_bias'] = 0.0
config_fashion['conv_filters_dim'] = 4
config_fashion['latent_dim'] = 20
config_fashion['num_cluster'] = 14
config_fashion['work_dir'] = 'results_dsprites'
config_fashion['save_every_epoch'] = 10000
config_fashion['e_noise'] = 'add_noise'
config_fashion['GS'] = 'GS'
config_fashion['noise'] = 'fl'
config_fashion['clamp_lower'] = -0.01
config_fashion['clamp_upper'] = 0.01
config_fashion['is_sklearn'] = False
config_fashion['Cluster'] = 'KMeans'
config_fashion['e_arch'] = 'dcgan'
config_fashion['name'] = 'MNIST'
config_fashion['optimizer'] = 'ADM'
config_fashion['range'] = 4

config_usps = {}
config_usps['data_shape'] = [16, 16, 1]
config_usps['batch_size'] = 300
config_usps['batch_norm'] = True
config_usps['batch_norm_eps'] = 1e-05
config_usps['batch_norm_decay'] = 0.9
config_usps['e_num_filters'] = 128
config_usps['e_num_layers'] = 4
config_usps['g_num_filters'] = 128
config_usps['g_num_layers'] = 4
config_usps['d_num_filters'] = 512
config_usps['d_num_layers'] = 4
config_usps['adam_beta1'] = 0.5
config_usps['lr'] = 0.002
config_usps['lr_adv'] = 0.002
config_usps['epoch_num'] = 1200
config_usps['print_every'] = 200
config_usps['init_std'] = 0.0099999
config_usps['init_bias'] = 0.0
config_usps['conv_filters_dim'] = 4
config_usps['latent_dim'] = 10
config_usps['num_cluster'] = 30
config_usps['work_dir'] = 'results_dsprites'
config_usps['save_every_epoch'] = 10000
config_usps['e_noise'] = 'add_noise'
config_usps['GS'] = 'GS'
config_usps['noise'] = 'fl'
config_usps['clamp_lower'] = -0.01
config_usps['clamp_upper'] = 0.01
config_usps['is_sklearn'] = False
config_usps['Cluster'] = 'KMeans'
config_usps['e_arch'] = 'dcgan'
config_usps['name'] = 'usps'
config_usps['optimizer'] = 'ADM'

config_cifar10 = {}
config_cifar10['data_shape'] = [32, 32, 3]
config_cifar10['batch_size'] = 100
config_cifar10['batch_norm'] = True
config_cifar10['batch_norm_eps'] = 1e-05
config_cifar10['batch_norm_decay'] = 0.9
config_cifar10['e_num_filters'] = 1024
config_cifar10['e_num_layers'] = 5
config_cifar10['g_num_filters'] = 1024
config_cifar10['g_num_layers'] = 5
config_cifar10['d_num_filters'] = 512
config_cifar10['d_num_layers'] = 3
config_cifar10['adam_beta1'] = 0.5
config_cifar10['lr'] = 0.002
config_cifar10['lr_adv'] = 0.002
config_cifar10['epoch_num'] = 800
config_cifar10['print_every'] = 200
config_cifar10['init_std'] = 0.0099999
config_cifar10['init_bias'] = 0.0
config_cifar10['conv_filters_dim'] = 3
config_cifar10['latent_dim'] = 30
config_cifar10['num_cluster'] = 10
config_cifar10['work_dir'] = 'results_dsprites'
config_cifar10['save_every_epoch'] = 10000
config_cifar10['e_noise'] = 'add_noise'
config_cifar10['GS'] = 'LINE'
config_cifar10['noise'] = 'fl'
config_cifar10['clamp_lower'] = -0.01
config_cifar10['clamp_upper'] = 0.01
config_cifar10['is_sklearn'] = False
config_cifar10['Cluster'] = 'KMeans'
config_cifar10['e_arch'] = 'dcgan'
config_cifar10['name'] = 'CIFAR10'
config_cifar10['optimizer'] = 'ADM'

config_reuters10k = {}
config_reuters10k['data_shape'] = [2000]
config_reuters10k['batch_size'] = 100
config_reuters10k['batch_norm'] = True
config_reuters10k['batch_norm_eps'] = 1e-05
config_reuters10k['batch_norm_decay'] = 0.9
config_reuters10k['e_num_filters'] = [256,128,64,32]
config_reuters10k['e_num_layers'] = 4
config_reuters10k['g_num_filters'] = [32,64,128,256]
config_reuters10k['g_num_layers'] = 4
config_reuters10k['adam_beta1'] = 0.5
config_reuters10k['d_num_filters'] = 512
config_reuters10k['d_num_layers'] = 4
config_reuters10k['lr'] = 0.002
config_reuters10k['lr_adv'] = 0.002
config_reuters10k['epoch_num'] = 1200
config_reuters10k['print_every'] = 100
config_reuters10k['init_std'] = 0.0099999
config_reuters10k['init_bias'] = 0.0
config_reuters10k['conv_filters_dim'] = 4
config_reuters10k['latent_dim'] = 10
config_reuters10k['num_cluster'] = 4
config_reuters10k['work_dir'] = 'results_dsprites'
config_reuters10k['save_every_epoch'] = 10000
config_reuters10k['e_noise'] = 'add_noise'
config_reuters10k['GS'] = 'GS'
config_reuters10k['noise'] = 'fl'
config_reuters10k['clamp_lower'] = -0.01
config_reuters10k['clamp_upper'] = 0.01
config_reuters10k['is_sklearn'] = False
config_reuters10k['Cluster'] = 'KMeans'
config_reuters10k['e_arch'] = 'mlp'
config_reuters10k['optimizer'] = 'ADM'
config_reuters10k['name'] = 'reuters10k'
config_reuters10k['lambda'] = 2
config_reuters10k['no_sample'] = 7

config_reuters = {}
config_reuters['data_shape'] = [2000]
config_reuters['batch_size'] = 150
config_reuters['batch_norm'] = True
config_reuters['batch_norm_eps'] = 1e-05
config_reuters['batch_norm_decay'] = 0.9
# config_reuters['e_num_filters'] = [512,256,128,64]
# config_reuters['e_num_layers'] = 4
# config_reuters['g_num_filters'] = [64,128,256,512]
# config_reuters['g_num_layers'] = 4
config_reuters['e_num_filters'] = [500,500,2000]
config_reuters['e_num_layers'] = 3
config_reuters['g_num_filters'] = [2000,500,500]
config_reuters['g_num_layers'] = 3

config_reuters['d_num_filters'] = 512
config_reuters['d_num_layers'] = 4
config_reuters['adam_beta1'] = 0.5
config_reuters['lr'] = 0.0005
config_reuters['lr_adv'] = 0.0005
config_reuters['epoch_num'] = 1000
config_reuters['print_every'] = 1000
config_reuters['init_std'] = 0.0099999
config_reuters['init_bias'] = 0.0
config_reuters['conv_filters_dim'] = 4
config_reuters['latent_dim'] = 30
config_reuters['num_cluster'] = 4
config_reuters['work_dir'] = 'results_dsprites'
config_reuters['save_every_epoch'] = 10000
config_reuters['e_noise'] = 'add_noise'
config_reuters['GS'] = 'GS'
config_reuters['noise'] = 'fl'
config_reuters['clamp_lower'] = -0.01
config_reuters['clamp_upper'] = 0.01
config_reuters['is_sklearn'] = False
config_reuters['Cluster'] = 'KMeans'
config_reuters['e_arch'] = 'mlp'
config_reuters['optimizer'] = 'ADM'
config_reuters['name'] = 'reuters10k'
config_reuters['lambda'] = 2
config_reuters['no_sample'] = 7



config_hhar = {}
config_hhar['data_shape'] = [561]
config_hhar['batch_size'] = 100
config_hhar['batch_norm'] = True
config_hhar['batch_norm_eps'] = 1e-05
config_hhar['batch_norm_decay'] = 0.9
# config_hhar['e_num_filters'] = [256,128,64]
# config_hhar['e_num_layers'] = 3
# config_hhar['g_num_filters'] = [64,128,256]
# config_hhar['g_num_layers'] = 3

# config_hhar['e_num_filters'] = [128,64]
# config_hhar['e_num_layers'] = 2
# config_hhar['g_num_filters'] = [64,128]
# config_hhar['g_num_layers'] = 2

config_hhar['e_num_filters'] = [1024,512]
config_hhar['e_num_layers'] = 2
config_hhar['g_num_filters'] = [512,1024]
config_hhar['g_num_layers'] = 2

config_hhar['d_num_filters'] = 512
config_hhar['d_num_layers'] = 3
config_hhar['adam_beta1'] = 0.5
config_hhar['lr'] = 0.002
config_hhar['lr_adv'] = 0.002
config_hhar['epoch_num'] = 1600
config_hhar['print_every'] = 100
config_hhar['init_std'] = 0.0099999
config_hhar['init_bias'] = 0.0
config_hhar['conv_filters_dim'] = 4
config_hhar['latent_dim'] = 20
config_hhar['num_cluster'] = 6
config_hhar['work_dir'] = 'results_dsprites'
config_hhar['save_every_epoch'] = 10000
config_hhar['e_noise'] = 'add_noise'
config_hhar['GS'] = 'GS'
config_hhar['noise'] = 'fl'
config_hhar['clamp_lower'] = -0.01
config_hhar['clamp_upper'] = 0.01
config_hhar['is_sklearn'] = False
config_hhar['Cluster'] = 'KMeans'
config_hhar['e_arch'] = 'mlp'
config_hhar['name'] = 'hhar'
config_hhar['optimizer'] = 'ADM'


config_svhn = {}
config_svhn['data_shape'] = [32, 32, 3]
config_svhn['batch_size'] = 100
config_svhn['batch_norm'] = True
config_svhn['batch_norm_eps'] = 1e-05
config_svhn['batch_norm_decay'] = 0.9
config_svhn['e_num_filters'] = 1024
config_svhn['e_num_layers'] = 5
config_svhn['g_num_filters'] = 1024
config_svhn['g_num_layers'] = 5
config_svhn['d_num_filters'] = 512
config_svhn['d_num_layers'] = 3
config_svhn['adam_beta1'] = 0.5
config_svhn['lr'] = 0.002
config_svhn['lr_adv'] = 0.002
config_svhn['epoch_num'] = 900
config_svhn['print_every'] = 200
config_svhn['init_std'] = 0.0099999
config_svhn['init_bias'] = 0.0
config_svhn['conv_filters_dim'] = 4
config_svhn['latent_dim'] = 20
config_svhn['num_cluster'] = 10
config_svhn['work_dir'] = 'results_dsprites'
config_svhn['save_every_epoch'] = 10000
config_svhn['e_noise'] = 'add_noise'
config_svhn['GS'] = 'LINE'
config_svhn['noise'] = 'fl'
config_svhn['clamp_lower'] = -0.01
config_svhn['clamp_upper'] = 0.01
config_svhn['is_sklearn'] = False
config_svhn['Cluster'] = 'KMeans'
config_svhn['e_arch'] = 'dcgan'
config_svhn['name'] = 'CIFAR10'
config_svhn['optimizer'] = 'ADM'
config_svhn['range'] = 4

config_stl = {}
config_stl['data_shape'] = [3, 96, 96]
config_stl['batch_size'] = 100
config_stl['batch_norm'] = True
config_stl['batch_norm_eps'] = 1e-05
config_stl['batch_norm_decay'] = 0.9
config_stl['e_num_filters'] = 512
config_stl['e_num_layers'] = 5
config_stl['g_num_filters'] = 512
config_stl['g_num_layers'] = 5
config_stl['d_num_filters'] = 512
config_stl['d_num_layers'] = 3
config_stl['adam_beta1'] = 0.5
config_stl['lr'] = 0.0005
config_stl['lr_adv'] = 0.0005
config_stl['epoch_num'] = 1600
config_stl['print_every'] = 200
config_stl['init_std'] = 0.0099999
config_stl['init_bias'] = 0.0
config_stl['conv_filters_dim'] = 4
config_stl['latent_dim'] = 30
config_stl['num_cluster'] = 10
config_stl['work_dir'] = 'results_dsprites'
config_stl['save_every_epoch'] = 10000
config_stl['e_noise'] = 'add_noise'
config_stl['GS'] = 'GS'
config_stl['noise'] = 'fl'
config_stl['clamp_lower'] = -0.01
config_stl['clamp_upper'] = 0.01
config_stl['is_sklearn'] = False
config_stl['Cluster'] = 'KMeans'
config_stl['e_arch'] = 'dcgan'
config_stl['name'] = 'stl'
config_stl['optimizer'] = 'ADM'
